service: slack-backup
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-1

# you can add statements to the Lambda function's IAM Role here
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - "arn:aws:s3:::splathon-slack-exports"
            - "arn:aws:s3:::splathon-slack-exports/*"
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource:
            - "*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  persistMessage:
    handler: bin/persistMessage
    events:
      - sqs:
          arn: !GetAtt SlackMessageJsonPutQueue.Arn

resources:
  Resources:
    SlackMessageJsonPutQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: slack-message-json-put
    SlackExports:
      Type: AWS::S3::Bucket
      DependsOn:
        - SQSPolicy
      Properties:
        BucketName: splathon-slack-exports
        NotificationConfiguration:
          QueueConfigurations:
            - Event: s3:ObjectCreated:Put
              Queue: !GetAtt SlackMessageJsonPutQueue.Arn
    SQSPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref SlackMessageJsonPutQueue
        PolicyDocument:
          Statement:
            - Action:
              - SQS:SendMessage
              Effect: Allow
              Resource: !GetAtt SlackMessageJsonPutQueue.Arn
              Principal:
                AWS:
                  - 858526741469
                Service:
                  - s3.amazonaws.com
    SlackMessage:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: ClientMessageID
            AttributeType: S
          - AttributeName: Channel
            AttributeType: S
          - AttributeName: User
            AttributeType: S
          - AttributeName: Timestamp
            AttributeType: N
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: ClientMessageID
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ChannelTimestampIDX
            KeySchema:
              - AttributeName: Channel
                KeyType: HASH
              - AttributeName: Timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: UserTimestampIDX
            KeySchema:
              - AttributeName: User
                KeyType: HASH
              - AttributeName: Timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        TableName: splathon-slack-message
